version: 2.1
references:
  workspace_root: &workspace_root ~/dhruvi
  container_config: &container_config
    working_directory: *workspace_root
    docker:
      - image: cimg/base:2023.03
  env_var: &env_var
    run:
      command: |
        export IMAGE_TAG_PREFIX=$(echo branch-$CIRCLE_BRANCH | sed 's/\//-/' )
        echo "export IMAGE_NAME=dhruvi007/cci_testing" >> $BASH_ENV
        echo "export IMAGE_TAG=$IMAGE_TAG_PREFIX-${CIRCLE_SHA1:0:7}" >> $BASH_ENV
        source $BASH_ENV
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - *env_var
      - run:
          name: building docker image
          command: | 
            docker build -t "$IMAGE_NAME:$IMAGE_TAG" -f Dockerfile .
      - run:
          name: running container
          command: docker run "$IMAGE_NAME:$IMAGE_TAG"
      
  push:
    <<: *container_config
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - *env_var
      - run:
          name: push docker image
          command: | 
            echo "$DH_PASS" | docker login -u "$DH_USER" --password-stdin
            docker push "$IMAGE_NAME:$IMAGE_TAG"


workflows:
  build_and_run:
    jobs:
      - build
      - push:
          requires: 
            - build