name: creating docker image


on:
  push:
    branches: main

jobs:
  building-image:
    name: building docker image
    runs-on: ubuntu-latest
    steps:
        - name: checking out
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: building image
          run: docker build -t $IMAGE_NAME -f Dockerfile .
          env:
            IMAGE_NAME: dhruvi007/ga_testing